# This file was generated by the {rix} R package v0.16.0 on 2025-10-30
# with following call:
# >rix(date = "2025-10-27",
#  > r_pkgs = c("bayesplot",
#  > "brms",
#  > "ggplot2",
#  > "magrittr",
#  > "posterior",
#  > "quarto",
#  > "rmarkdown",
#  > "targets",
#  > "tarchetypes"),
#  > system_pkgs = c("quarto",
#  > "git",
#  > "cmdstan"),
#  > git_pkgs = list(list(package_name = "cmdstanr",
#  > repo_url = "https://github.com/stan-dev/cmdstanr",
#  > commit = "da99e2ba954658bdad63bffb738c4444c33a4e0e")),
#  > tex_pkgs = c("amsmath"),
#  > ide = "radian",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-10-27.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      bayesplot
      brms
      ggplot2
      magrittr
      posterior
      quarto
      rmarkdown
      tarchetypes
      targets;
  };
 
    cmdstanr = (pkgs.rPackages.buildRPackage {
      name = "cmdstanr";
      src = pkgs.fetchgit {
        url = "https://github.com/stan-dev/cmdstanr";
        rev = "da99e2ba954658bdad63bffb738c4444c33a4e0e";
        sha256 = "sha256-wXfOxBexnuL83fvCM+6qv6d7UhTLGq+Xhvja3lRfQpI=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          checkmate
          data_table
          jsonlite
          posterior
          processx
          R6
          withr
          rlang;
      };
    });
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath;
  });
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      cmdstan
      git
      glibcLocales
      nix
      quarto
      R
      which
      pandoc;
  };
 
  wrapped_pkgs = pkgs.radianWrapper.override {
    packages = [ cmdstanr rpkgs  ];
  };
 
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ cmdstanr rpkgs tex  system_packages  wrapped_pkgs ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
